### PR TITLE
Open with Visual Studio Version 17.5.3

### LINKED ISSUE #37: Build binaries for each commit using GitHub Actions
I tried in my this branch, and it looks work.

https://github.com/takano32/PSXPackager/tree/develop-GitHub-Actions

It makes download binaries available for each commit at the bottom of GitHub Actions Summary page.

* https://github.com/takano32/PSXPackager/actions/runs/4656245990
* https://github.com/takano32/PSXPackager/actions/runs/4656245992

I'll create PR with these commit after #36 merging.

* https://github.com/takano32/PSXPackager/commit/45da651d92242250c09409d109fdfea46a9b5767
* https://github.com/takano32/PSXPackager/commit/9a80f84c393a2eb4a59854ad8f88b32b2deaa119
* https://github.com/takano32/PSXPackager/commit/a667aeb0d31d462fd026fffcfc16a5c50cb856d9
* https://github.com/takano32/PSXPackager/commit/40ddcc75a8d86da4c71e3c01083a65bf5aa22197

### PR DESCRIPTION
**Pull request by takano32**
Update Packages and Update Projects

I’ll make this Ready for review after simple test in Linux and macOS.

* GitHub Actions
* UnitTest

closes #37

### CODE REVIEW

**Comment by RupertAvery** [comment]
Oops, sorry accidentally marked as ready for review

**Comment by takano32** [comment]
@RupertAvery No, don't worry about it.
Sorry it took me a little while to get back to you.
I was able to run make in Git Bash to create a binary and confirm that it works.
This is now ready for preview, actually.

Thanks always.

**Comment by takano32** [comment]
@RupertAvery Please feel free to point out any corrections if they are.

**Comment by takano32** [comment]
I included #37 in this PR. 

It may be difficult to review with large differences. Sorry.

closes #37

**Comment by takano32** [comment]
I confirmed `gui-win-x64` and `win-x64` binaries downloading from GitHub Actions Summary work well in my old LapTop installed Windows 10.

https://github.com/takano32/PSXPackager/actions/runs/4688277339

LGTM! :bow:

**Review by RupertAvery — APPROVED** [review]

**Comment by takano32** [comment]
Thank you for merging!

And GitHub Actions started generating binaries in this Repo! 🎉 

https://github.com/RupertAvery/PSXPackager/actions

**Pull request merged**
